entrevue/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic import TemplateView

from django.contrib import admin
admin.autodiscover()

from rdv.views import *

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'entrevue.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^answer$', AnswerView.as_view(), name="answer"),
    url(r'^repropose$', ReproposeView.as_view(), name="repropose"),
    url(r'^(?P<rdvid>[-A-Za-z0-9_]+)$', RDVView.as_view(), name="rdv_page"),
    url(r'^$', IndexView.as_view(), name="index"),
    url(r'^cockpit/', include(admin.site.urls)),
)

rdv/models.py
#-*- coding: utf-8 -*-

from django.db import models

from rdv.random_primary import RandomPrimaryIdModel


class Answer(models.Model):
    YES = 'y'
    NO = 'n'
    OTHER = 'o'

    ANS_CHOICES = ( 
            (YES, "Yes"), 
            (NO, "No"), 
            (OTHER, "Other"),
        )

    date = models.DateTimeField(auto_now_add=True)
    value = models.CharField(max_length=1, 
                            choices=ANS_CHOICES)
    answerer = models.CharField(max_length=256, blank=True, null=True)


class RDV(RandomPrimaryIdModel):
    creation = models.DateTimeField(auto_now_add=True)
    title = models.CharField(max_length=256, blank=True, null=True, verbose_name='Titre')
    proposer = models.CharField(max_length=256, blank=True, null=True, verbose_name='Nom')
    proposed_date = models.DateTimeField(auto_now_add=False, blank=False, null=False, verbose_name='Date choisie (obligatoire)')
    initial_rdv = models.ForeignKey('rdv.RDV', related_name='counter_proposition', blank=True, null=True)
    answer = models.ForeignKey(Answer, null=True, blank=True)
    email_creator = models.EmailField(blank=True, null=True, verbose_name='Email pour être averti des réponses (sera masqué)')
    email_share = models.EmailField(blank=True, null=True, verbose_name='Email pour partager le rendez-vous (sera masqué)')
    place = models.CharField(max_length=256, blank=True, null=True, verbose_name='Lieu')

rdv/forms.py
#-*- coding: utf-8 -*-


import datetime
import locale

from django import forms

from rdv.models import RDV
from rdv.widgets import DateWidget


class RDVForm(forms.ModelForm):
    class Meta:
        model = RDV
        fields = [
                    'title',
                    'proposer', 
                    'proposed_date', 
                    'place',
                    'email_creator', 
                    'email_share', 
                ]
        widgets = {
            'proposed_date': DateWidget(attrs={
                'placeholder': ['Quel jour ?', 'Quelle heure ?']
            }),
            'proposer': forms.TextInput(attrs={'placeholder': 'Qui propose ?'}),
            'title': forms.TextInput(attrs={'placeholder': 'Quel titre pour ce rendez-vous ?'}),
            'place': forms.TextInput(attrs={'placeholder': u'Où ?'}),
            'email_creator': forms.TextInput(attrs={'placeholder': 'expe@email'}),
            'email_share': forms.TextInput(attrs={'placeholder': 'dest@email'}),
        }

    def __init__(self, notitle=False, *args, **kwargs):
        inst = kwargs.pop("instance", None)

        super(RDVForm, self).__init__(*args, **kwargs)

        if inst is not None:
            self.fields['place'].initial = inst.place
            self.fields['email_creator'].initial = inst.email_share
            # locale.setlocale(locale.LC_ALL, 'fr_FR')
            self.fields['proposed_date'].widget.widgets[0].attrs['data-value'] = inst.proposed_date.strftime("%Y-%m-%d")
            self.fields['proposed_date'].widget.widgets[1].attrs['data-value'] = inst.proposed_date.strftime("%H:%M")

        if notitle:
            del self.fields['title']

    def clean(self):
        date = " ".join([self.data.get('proposed_date_0'), self.data.get('proposed_date_1')])
        cleaned_data = super(RDVForm, self).clean()

        if len(self.data.get('proposed_date_1')) > 1:
            proposed_date = datetime.datetime.strptime(date, '%Y-%m-%d %H:%M')
        else:
            # Ou générer une erreur pour heure non rentrée
            proposed_date = datetime.datetime.strptime(date.replace(' ', ''), '%Y-%m-%d')

        if isinstance(proposed_date, datetime.datetime) and 'proposed_date' in self.errors.keys():
            del self.errors['proposed_date']

        cleaned_data.update({
            'proposed_date': proposed_date.strftime('%Y-%m-%d %H:%M:%S'),
        })

        return cleaned_data

rdv/views.py
#-*- coding: utf-8 -*-

from django.shortcuts import render, redirect, get_object_or_404

# 
# from django.template import RequestContext
# from django.core import serializers
# from django.utils import simplejson
# from django.core.exceptions import ObjectDoesNotExist
# 
# from django.contrib import messages
# from django.contrib.auth import authenticate
# from django.contrib.auth.models import User
# from django.contrib.auth import login, logout

from django.views.generic import TemplateView
from django.views.generic.edit import CreateView
from django.core.exceptions import ValidationError
from django.core.validators import validate_email

from datetime import datetime

from rdv.models import RDV, Answer
from rdv.forms import RDVForm
from rdv.mail import mail_rdv_created, mail_rdv_edited, mail_rdv_answered, mail_invitation


class IndexView(CreateView):
    template_name = "rdv/index.html"
    model = RDV
    form_class = RDVForm
    fields = ['proposed_date', 'proposer', 'place']

    def post(self, request, *args, **kwargs):
        return super(IndexView, self).post(request, *args, **kwargs)

    def form_valid(self, form):
        self.object = form.save()
        self.object.save()
        email_from = form.cleaned_data['email_creator']
        email_to = form.cleaned_data['email_share']

        mail_rdv_created(self.object, [email_from]) 
        mail_invitation(self.object, [email_to])

        self.success_url = "/" + str(self.object.id)
        return redirect(self.get_success_url())

    def get_context_data(self, *args, **kwargs):
        context = super(IndexView, self).get_context_data(*args, **kwargs)
        context["rdv_list"] = RDV.objects.all()
        if self.object != None:
            context['new_rdv'] = self.object
            context['rdv_created'] = True

        return context


class AnswerView(TemplateView):
    template_name = "rdv/answer.html"
    
    def get(self, request, *args, **kwargs):
        context = self.get_context_data(**kwargs)
        # Check if the rendez-vous id is in the parameters
        if "rdvid" not in request.GET.keys():
            # Manage error here 
            # TODO
            print "No rdvid given."
            return self.render_to_response(context)

        # Get rendez-vous object
        rdv = RDV.objects.get(id=request.GET["rdvid"])

        # Get the name of the proposer
        if "answerer" in request.GET.keys():
            nickname = request.GET["answerer"]
        else:
            nickname = ""

        # Check if the answer is in the parameters
        if "ynanswer" not in request.GET.keys():
            # Manage error here 
            # TODO
            print "No ynanswer given."
            return self.render_to_response(context)

        if request.GET["ynanswer"] == 'y':
            # Create a yes answer object
            ans = Answer(value='y', answerer=nickname)
        elif request.GET["ynanswer"] == 'n':
            # Create a no answer object
            ans = Answer(value='n', answerer=nickname)
        else: 
            # idem
            # TODO
            print "Answer not y nor no."
            return self.render_to_response(context)


        ans.save()
        rdv.answer = ans
        rdv.save()

        email_to = list()

        # Get initial rdv
        initial_rdv = rdv
        while initial_rdv.initial_rdv != None:
            initial_rdv = initial_rdv.initial_rdv

        try:
            validate_email(str(rdv.email_creator))
        except ValidationError as e:
            pass
        else:
            email_to.append(str(rdv.email_creator))

        # Envoi d'email pour notifier de la réponse
        mail_rdv_answered(initial_rdv, email_to)

        return redirect("/" + str(initial_rdv.id))


class ReproposeView(TemplateView):
    def post(self, request, *args, **kwargs):

        new_rdv_form = RDVForm(data=request.POST)
        if new_rdv_form.is_valid():
            # Check if the rendez-vous id is in the parameters
            if "rdvid" not in request.POST.keys():
                # Manage error here
                # TODO
                print "No rdvid given."
                return redirect('index')

            # Get initial proposition
            rdv = RDV.objects.get(id=request.POST['rdvid'])

            # Then we try to reach the last proposition
            curr_prop = rdv
            # While there is a previous proposition
            while len(curr_prop.counter_proposition.all()) > 0:
                # We take one step back
                curr_prop = curr_prop.counter_proposition.all()[0]

            # At this point, rdv is the initial proposition and 
            # curr_prop is the current one

            # Get the name of the proposer
            if "nickname" in request.POST.keys():
                nickname = request.POST["nickname"]
            else:
                nickname = ""

            # Creation of an answer for the current proposition
            ans = Answer(answerer=nickname, value='o')
            # Saving the answer
            ans.save()
            # Linking answer to the proposition
            curr_prop.answer = ans
            curr_prop.save()

            # Next, we create the new proposition

            # Get the date string
    #        date_str = request.GET["proposed_date"]
            # Create the date object
    #        date = datetime.strptime(date_str, "%m/%d/%Y")
            # Get the date
    #        place = request.GET["place"]
            # Create the new rdv object linked to the previous proposition
            new_rdv = new_rdv_form.save(commit=False)
            new_rdv.initial_rdv = curr_prop
            new_rdv.title = rdv.title
            new_rdv.save()

            # Notification by email for a new proposition
            mail_rdv_edited(rdv, [str(curr_prop.email_creator)])

            # Redirect to the page of the initial proposition
            return redirect('rdv_page', rdvid=str(rdv.id))


class RDVView(TemplateView):
    template_name = "rdv/rdv_page.html"

    def get(self, request, *args, **kwargs):
        context = self.get_context_data(**kwargs)
        rdvid = self.kwargs['rdvid']
        context["rdvid"] = rdvid
        rdv = RDV.objects.get(id=rdvid)
        context["previous_rdv"] = list()
        while len(rdv.counter_proposition.all()) > 0:
            context["previous_rdv"].append(rdv)
            rdv = rdv.counter_proposition.all()[0]
        context["rdv"] = rdv 
        context["form"] = RDVForm(notitle=True, instance=rdv)
        return self.render_to_response(context)

    model = RDV
    slug_field = 'pk'
    slug_url_kwarg = 'rdvid'
    context_object_name = "rdv"


class CreatedView(TemplateView):
    template_name = "rdv/created.html"

rdv/templates/rdv/base.html
<!DOCTYPE HTML>

{% load staticfiles %}

<head>
    <link href='http://fonts.googleapis.com/css?family=Roboto:400,300,100' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="{% static 'rdv/css/animate.min.css' %}" />
    <link rel="stylesheet" href="{% static 'rdv/css/font-awesome.min.css' %}" />
    <link rel="stylesheet" href="{% static 'rdv/css/bootstrap.min.css' %}" />
    <link rel="stylesheet" href="{% static 'rdv/css/datepicker.css' %}" />
    <link rel="stylesheet" href="{% static 'rdv/css/bootstrap-timepicker.min.css' %}" />
    <link rel="stylesheet" href="{% static 'rdv/libs/pickadate/themes/default.css' %}" />
    <link rel="stylesheet" href="{% static 'rdv/libs/pickadate/themes/default.date.css' %}" />
    <link rel="stylesheet" href="{% static 'rdv/libs/pickadate/themes/default.time.css' %}" />
    <link rel="stylesheet" href="{% static 'rdv/generated/css/style.css' %}" />

    <script src="{% static 'rdv/js/jquery.min.js' %}"></script>
    <script src="{% static 'rdv/libs/pickadate/picker.js' %}"></script>
    <script src="{% static 'rdv/libs/pickadate/picker.time.js' %}"></script>
    <script src="{% static 'rdv/libs/pickadate/picker.date.js' %}"></script>
    <script src="{% static 'rdv/libs/pickadate/translations/fr_FR.js' %}"></script>

</head>

<body>
    {% block content %}
    {% endblock %}
</body>

</html>

rdv/templates/rdv/created.html
OK

rdv/templates/rdv/index.html
{% extends "rdv/base.html" %}
{% load tags %}

{% block content %}
    <hgroup>
        <h1 class="animated fadeInDown"> Entrevue </h1>
        <h4 class="animated fadeInDown"> Rendez vous dans deux clics </h4>
    </hgroup>

    <section>

        <article class="presentation active">
            <input class="validate create-rdv" type="button" value="Créer un rendez-vous"/>
            <table class="iconography">
                <tr class="keyword">
                    <td colspan="5">
                        <h1>Créez</h1>
                    </td>
                </tr>
                <tr class="icon">
                    <td>
                        <i class="fa circle fa-calendar"></i>
                    </td>
                    <td>
                        <i class="fa fa-plus"></i>
                    </td>
                    <td>
                        <i class="fa circle fa-clock-o"></i>
                    </td>
                    <td>
                        <i class="fa fa-plus"></i>
                    </td>
                    <td>
                        <i class="fa circle fa-map-marker"></i>
                    </td>
                </tr>
                <tr class="legend">
                    <td>
                        Un jour
                    </td>
                    <td>
                    </td>
                    <td>
                        Une heure
                    </td>
                    <td>
                    </td>
                    <td>
                        Un lieu
                    </td>
                </tr>
            </table>
            <i class="fa fa-long-arrow-down"></i>
            <table class="iconography">
                <tr class="keyword">
                    <td colspan="7">
                        <h1>Partagez</h1>
                    </td>
                </tr>
                <tr class="icon">
                    <td>
                        <i class="fa circle fa-send"></i>
                    </td>
                    <td></td>
                    <td>
                        <i class="fa circle fa-fax"></i>
                    </td>
                    <td></td>
                    <td>
                        <i class="fa circle fa-envelope"></i>
                    </td>
                    <td></td>
                    <td>
                        <i class="fa circle fa-mobile-phone"></i>
                    </td>
                </tr>
                <tr class="legend">
                    <td>
                        Email
                    </td>
                    <td></td>
                    <td>
                        Fax
                    </td>
                    <td></td>
                    <td>
                        Courrier
                    </td>
                    <td></td>
                    <td>
                        SMS
                    </td>
                </tr>
            </table>
            <i class="fa fa-long-arrow-down"></i>
            <table class="iconography">
                <tr class="keyword">
                    <td colspan="5">
                        <h1>Répondez</h1>
                    </td>
                </tr>
                <tr class="icon">
                    <td>
                        <i class="fa circle fa-check-circle"></i>
                    </td>
                    <td></td>
                    <td>
                        <i class="fa circle fa-times-circle"></i>
                    </td>
                    <td></td>
                    <td>
                        <i class="fa circle fa-edit"></i>
                    </td>
                </tr>
                <tr class="legend">
                    <td>
                        Acceptez
                    </td>
                    <td></td>
                    <td>
                        Refusez
                    </td>
                    <td></td>
                    <td>
                        Modifiez
                    </td>
                </tr>
            </table>
            <input class="validate create-rdv" type="button" value="Créer un rendez-vous"/>

        </article>

        <article class="propose">
            <form action="{% url 'index' %}" method="post" id="rdvForm">
                {% csrf_token %}
                {% for field in form %}
                    <div class="input-group {% if field.errors %}warning{% endif %}">
                        <label for="{{ field.name }}">{{ field.label }}{% if field.errors %} ({% for error in field.errors %}{{ error }}{% if forloop.counter != field.errors|length %}/{% endif %}{% endfor %}){% endif %}</label>
                        {{ field }}
                    </div>
                {% endfor %}
                <input class="validate" type="submit" value="Créer le rendez-vous"/>
            </form>
        </article>
    </section>

   <script>
        $(document).ready(function () {
            $('#id_proposed_date_0').pickadate({
                close: 'Fermer',
                formatSubmit: 'yyyy-mm-dd',
                hiddenName: true
            });
            $('#id_proposed_date_1').pickatime({
                editable: true,
                formatSubmit: 'H:i',
                format: 'H:i',
                hiddenName: true
            });
            $(".create-rdv").click(function() {
                $('.presentation').toggleClass('animated fadeOutLeft'); 
                setTimeout(function() {
                    $('.presentation').toggleClass('active');
                    $('.propose').toggleClass('active animated fadeInRight');
                }, 1000);
                setTimeout(function() {
                    $('.propose').toggleClass('animated fadeInRight');
                }, 2000);
            });
        });

    </script>
{% endblock %}

rdv/templates/rdv/rdv_page.html
{% extends "rdv/base.html" %}
{% load isinstance %}

{% block content %}
    <a class="backlink animated fadeIn" href="{% url 'index' %}" title="Proposer un rdv"><span class="glyphicon glyphicon-home"> </span></a>
    <hgroup class="not-home">
        <h4 class="animated fadeInDown">Hey, tu viens ? </h4>
    </hgroup>

    <section>
        <h1>
            {% if rdv.title != None and rdv.title != "" %}
               {{ rdv.title }}
            {% else %}
                Ton rendez-vous !
            {% endif %}
        </h1>

        {% for prev in previous_rdv %}
            <p>
                {% if prev.proposer == None or prev.proposer == "" %}
                    Un rendez-vous a été proposé le {{ prev.proposed_date }}{% if prev.place != "" %} à {{ prev.place }}{% endif %}.
                {% else %}
                    {{ prev.proposer }} a proposé un rendez-vous le {{ prev.proposed_date }}{% if prev.place != "" %} à {{ prev.place }}{% endif %}.
                {% endif %}
            </p>
        {% endfor%}

        <p class="last_prop">
            {% if rdv.proposer == None or rdv.proposer == "" %}
                Un rendez-vous a été proposé le {{ rdv.proposed_date }}{% if rdv.place != "" %} à {{ rdv.place }}{% endif %}.
            {% else %}
                {{ rdv.proposer }} a proposé un rendez-vous le {{ rdv.proposed_date }}{% if rdv.place != "" %} à {{ rdv.place }} {% endif %}.
            {% endif %}
        </p>
        <p class="definitive_ans {% if rdv.answer|isYes %}yes{% elif rdv.answer|isNo %}no{% endif %}">
            {% if rdv.answer|isYes %}
                {% if rdv.answer.answerer == None or rdv.answer.answerer == "" %}
                    Le rendez-vous a été accepté.
                {% else %}
                    {{ rdv.answer.answerer }} a accepté le rendez-vous.
                {% endif %}
            {% elif rdv.answer|isNo %}
                {% if rdv.answer.answerer == None or rdv.answer.answerer == "" %}
                    Le rendez-vous a été décliné.
                {% else %}
                    {{ rdv.answer.answerer }} a décliné le rendez-vous.
                {% endif %}
            {% endif %}
        </p>

        {% if not rdv.answer|isYes and not rdv.answer|isNo %}
            <form action="{% url 'answer' %}" method="get" id="answerForm">
                {% csrf_token %}
                <div class="input-group answerer">
                    <input id="id_answerer" maxlength="256" name="answerer" placeholder="Qui répond ?" type="text">
                </div>
                <input type="hidden" name="rdvid" value="{{ rdv.id }}" />
                <input type="hidden" name="ynanswer" id="ynanswer" value="" />
                <input class="yes validate" type="button" value="Accepter"><!--
                --><input class="no validate" type="button" value="Refuser">
            </form>

            <h2 id="or_repropose">ou</h2>
            <input class="validate js-repropose" type="button" value="Proposer une nouvelle date"/>
        <article class="repropose">
            <form action="{% url 'repropose' %}" method="POST" id="rdvForm">
                {% csrf_token %}
                <input type="hidden" name="rdvid" value="{{ rdvid }}">
                {% for field in form %}
                    {% if field.name != "email_share" %}
                        <div class="input-group {% if field.errors %}warning{% endif %}">
                            <label for="{{ field.name }}">{{ field.label }}{% if field.errors %} ({% for error in field.errors %}{{ error }}{% if forloop.counter != field.errors|length %}/{% endif %}{% endfor %}){% endif %}</label>
                            {{ field }}
                        </div>
                    {% endif %}
                {% endfor %}

                <input class="validate" type="submit" value="Proposer la nouvelle date"/>
            </form>
        {% endif %}
        </article>
    </section>

   <script>
        $(document).ready(function () {
            $('#id_proposed_date_0').pickadate({
                close: 'Fermer',
                formatSubmit: 'yyyy-mm-dd',
                hiddenName: true
            });
            $('#id_proposed_date_1').pickatime({
                editable: true,
                formatSubmit: 'H:i',
                format: 'H:i',
                hiddenName: true
            });
            $('#rdvForm').on('submit', function() {
                $(this).submit();
            });
            $(".yes", "#answerForm").click(function(e) {
                $("#ynanswer").val("y");
                $("#answerForm").submit();
            });
            $(".no", "#answerForm").click(function(e) {
                $("#ynanswer").val("n");
                $("#answerForm").submit();
            });
            $('.js-repropose').on('click', function() {
                $('.repropose').toggleClass('active animated fadeInUp');
                $( this ).toggleClass('hidden');
                setTimeout(function() {
                    $('.repropose').toggleClass('animated fadeInUp');
                }, 1000);
            });
        });
    </script>
{% endblock %}